[profile.default]
src = "src"
out = "out"
libs = ["lib"]
no_match_path = "test/Benchmarks.t.sol"
via_ir = true
optimizer_runs = 999999

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
